# Generated by Django 5.1.5 on 2025-09-14 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DriverLicence',
            new_name='DriverLicense',
        ),
    ]
