# Generated by Django 5.1.5 on 2025-09-14 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rename_driverlicence_driverlicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlicense',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='application.driverapplication'),
        ),
    ]
