# Generated by Django 5.1.5 on 2025-09-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_driverlicense_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverapplication',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('denied', 'Denied'), ('pending', 'Pending')], default='pending', max_length=255),
        ),
    ]
